export const DEFAULT_PREFIX = 'VITE_'
export const DEFAULT_GLOBAL_NAME = '__VITE_INJECT_ENV__'
export const DEFAULT_CONFIG_FILE = '__vite_env_config__.js'
export const DEFAULT_CONFIG_TEMPLATE = '__vite_env_config__.js.template'
export const DEFAULT_DOCKER_ENTRYPOINT = 'docker-entrypoint.sh'
export const INJECTED_SCRIPT_ATTR = 'data-vite-env-inject'
